import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import React from "react";
import type { GetServerSideProps } from "next";
import Model, { ModelProps } from "../components/Model";
import prisma from '../lib/prisma'

const inter = Inter({ subsets: ['latin'] })

export const getServerSideProps: GetServerSideProps = async () => {
  const feed = await prisma.datasheet_model.findMany({
    where: {
      datasheet_id: 61,
    }
  });
  return {
    props: { feed },
  };
};

type Props = {
  feed: ModelProps[];
};

const Home: React.FC<Props> = (props) => {
    return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.center}>
          {props.feed.map((model) => (
            <div key={model.id} className="post">
              <Model m={model} />
            </div>
          ))}
        </div>

      </main>
    </>
  )
}

export default Home;
